<?php
// autoload.php @generated by Composer

require_once "vendor/autoload.php";
\Tinify\setKey("YOUR-TINYPNG-KEY");

$dir = 'uncompressed/';
$images = scandir($dir);
$images = array_diff($images, array('.', '..'));

//aqui se redimensiona y se comprimen
///*
foreach ($images as $image) {

    $source = \Tinify\fromFile($dir . $image);
    $resized = $source->resize(array(
        "method" => "fit",
        "width" => 750,
        "height" => 750,
    ));
    $resized->toFile("compressed/" . $image);
}
echo "All images are redimensioned and compressed.";
//*/
//

//aqui solo se comprimen
/*
foreach ($images as $image) {
     $source = \Tinify\fromFile($dir . $image);
     $source->toFile("compressed/" . $image);
 }

echo "All images are compressed.";
*/
//
